## cluster parameters
# sbatch -c {threads} -J {rule}.snakemake
#            --mem-per-cpu={cluster.memory} -o {{cluster_logDir}}/{rule}.%j.out
#            -e {{cluster_logDir}}/{rule}.%j.err
#
cluster_cmd: 'qsub -V -cwd -j y -pe threaded {threads} -l h_vmem={cluster.memory},h_rt=24:00:00 -l tmpspace=100G -N {rule}.snakemake -S /bin/bash'
cluster_logDir: cluster_logs
latency_wait: 120
__default__:
    memory: 50G
STAR:
    memory: 90G
