## workflow parameters
# file name extension of input (raw) reads
ext: '.fastq.gz'
# The suffix added to input (raw) reads
reads: ["_R1","_R2"]
# List of cell barcodes
barcode_list:
# Path to genome fasta file
genome_fasta: '/hpc/hub_oudenaarden/vbhardwaj/annotations/hg38_gencode31_extra/genome_fasta/genome.fa'
# Path to GTF file
gtf_file: '/hpc/hub_oudenaarden/vbhardwaj/annotations/hg38_gencode31_extra/annotation/genes.gtf'
# regions to remove from signal extraction
blacklist_bed: "/hpc/hub_oudenaarden/vbhardwaj/annotations/blacklists/hg38-blacklist.v2.bed"
# minimum mapq threshold to extract signal from
min_mapq:
