## workflow parameters
# file name extension of input (raw) reads
ext: '.fastq.gz'
# The suffix added to input (raw) reads
reads: ["_R1","_R2"]
# List of cell barcodes
barcodes:
# Path to genome fasta file
genome_fasta: '/hpc/hub_oudenaarden/vbhardwaj/annotations/hg38_gencode31_extra/genome_fasta/genome.fa'
# Path to GTF file
genome_gtf: '/hpc/hub_oudenaarden/vbhardwaj/annotations/hg38_gencode31_extra/annotation/genes.gtf'
# minimum mapq threshold to extract signal from
min_mapq:
